name: build-push
run-name: ${{ github.actor }} is building Gram
on: [push]
jobs:
  print-runner-info:
    runs-on: arc-runner-set-gram
    steps:
        - uses: actions/checkout@v7
        - run: ls -la
        - name: Install Buildah
          run: | 
            sudo apt update
            sudo apt install -y buildah
        - name: Configure Buildah
          run: |
            podman system migrate
        - name: Build Image
          uses: redhat-actions/buildah-build@v3
          with:
            image: gram
            tags: v1 ${{ github.sha }}
            containerfiles: |
              ./Dockerfile
