name: build-push
run-name: ${{ github.actor }} is building Gram
on: [push]
jobs:
  print-runner-info:
    runs-on: arc-runner-set-gram
    steps:
        - uses: actions/checkout@v7
        - run: ls -la
        - name: Install Buildah
          run: | 
            sudo apt update
            sudo apt install -y podman
        - name: Configure Buildah
          run: |
            user=$(whoami)
            sudo usermod --add-subuids 100000-165535 $user
            sudo usermod --add-subgids 100000-165535 $user
            sudo podman system migrate
        - name: Build Image
          uses: redhat-actions/buildah-build@v3
          with:
            image: gram
            tags: v1 ${{ github.sha }}
            containerfiles: |
              ./Dockerfile
