name: Docker Image CI

on:
  [push]
jobs:

  build:

    runs-on: arc-runner-set-gram

    steps:
    - uses: actions/checkout@v4
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: .
        push: true
        tags: oci-registry.default.svc.cluster.local:5000/gram:${{ github.sha }}
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag oci-registry.pi.home/gram:$(git rev-parse --short HEAD)
    # - 
