name: Docker Image CI

on:
  push:
    branches: [ "main","gha" ]
  pull_request:
    branches: [ "main","gha" ]

jobs:

  build:

    runs-on: arc-runner-set-gram

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
